language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x ./gradlew

# Travis CI 서버의 Home
cache:
  directories:
    -  '$HOME/.m2/repository'
    -  '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/springwebservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: apink-springboot2-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip파일 접근을 private으로
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: apink-springboot2-build
    key: springwebservice.zip
    bundle_type: zip
    application: apink-springboot2-webservice
    deployment_group: apink-springboot2-webservice
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - iih907@naver.com